version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-one"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t88u40vyuian"
s3_prefix = "test-one"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"staging\""
image_repositories = []
