AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Globals:
  Function:
    Runtime: go1.x
    Environment:
      Variables:
        SCHEMA_BUCKET: !Join ["-", ["test-schema", !Ref Stage]]
        SUB_SCHEMA_BUCKET: !Join ["-", ["test-sub-schemas", !Ref Stage]]

Resources:
  ProxyHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 180
      Handler: handler
      CodeUri: handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/graphql'
            Method: post

  MasterSchemaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ["test-schema", !Ref Stage]]

  SubSchemaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ["test-sub-schemas", !Ref Stage]]
