AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Globals:
  Function:
    Runtime: go1.x
    Environment:
      Variables:
        SCHEMA_BUCKET: !Join ["-", ["master-schema", !Ref Stage]]
        SUB_SCHEMA_BUCKET: !Join ["-", ["sub-schemas", !Ref Stage]]

Resources:
  ProxyHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 180
      Handler: handlers/proxy
      CodeUri: handlers/proxy
      Policies:
        - Statement:
            - Effect: Allow
              Action:
              - s3:GetObject
              Resource: "*"   
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/graphql'
            Method: post

  MergeSchemas:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 180
      Handler: handlers/merge_schemas
      CodeUri: handlers/merge_schemas
      Policies:
        - Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource: "*"
      Events:
        SubSchemaUpdateEvent:
          Type: S3
          Properties:
            Bucket: !Ref SubSchemaBucket
            Events: s3:ObjectCreated:*


  MasterSchemaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ["master-schema", !Ref Stage]]

  SubSchemaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ["sub-schemas", !Ref Stage]]
